#use this file as an example of what to store locally for your producer
#should the producer be running in AWS, these will not be neccessary

aws:
  publicKey: 'String'
  secretKey: 'String'
  defaultRegionName: 'String'