spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  #main:
  #  banner-mode: off
selenium:
  chrome-driver-location: "/usr/src/app/chromedriver"
  testUrl: "https://google.com"
aws:
  sqsUrl: "https://sqs.eu-central-1.amazonaws.com/397254617684/crawler_queue"
  credentialsFile: "config/aws.json"
