# Generated by Django 3.1.5 on 2021-02-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210113_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='additional_data',
            field=models.TextField(default=''),
        ),
    ]
