# Generated by Django 2.2.16 on 2021-02-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00:00.000000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default='1970-01-01 00:00:00.000000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='parse_date',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
        migrations.AlterField(
            model_name='article',
            name='upload_date',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00:00.000000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default='1970-01-01 00:00:00.000000'),
            preserve_default=False,
        ),
    ]
