spring:
 # datasource:
 #   driver-class-name: org.h2.Driver
 #   url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
 #   username: admin
 #   password:
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  #main:
  #  banner-mode: off
  flyway:
    enabled: false
aws:
  sqsUrl: "https://sqs.eu-central-1.amazonaws.com/397254617684/crawler_queue"
  credentialsFile: "config/aws.json"
  region: "eu-central-1"
crawler-consumer:
  dbCredentialsFile: "config/consumerdb.json"
  databaseName: mdcrawler_consumer_d
  #be careful about docker networking here
  connectionUrl: "jdbc:mysql://192.168.5.159:3306/mdcrawler_consumer_d?serverTimezone=UTC"
