spring:
 # datasource:
 #   driver-class-name: org.h2.Driver
 #   url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  main:
    banner-mode: off
  flyway:
    enabled: false
springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    config-url: '/api-docs/swagger-config'
    url: '/api-docs'
    doc-expansion: none
    disable-swagger-default-url: true
aws:
  sqsUrl: "https://sqs.eu-central-1.amazonaws.com/397254617684/crawler_queue"
  credentialsFile: "config/aws.json"
  region: "eu-central-1"
crawler-consumer:
  dbCredentialsFile: "config/consumerdb.json"
  databaseName: mdcrawler_consumer_d
  #be careful about docker networking here
  connectionUrl: "jdbc:mysql://172.31.0.171:3306/mdcrawler_consumer_d?serverTimezone=UTC"
