spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  #main:
  #  banner-mode: off
aws:
  sqsUrl: "https://sqs.eu-central-1.amazonaws.com/397254617684/crawler_queue"
  credentialsFile: "config/aws.json"
  region: "eu-central-1"
